export const registerConfigs = [
  { address: 0, name: '当前烟雾', dataType: 'uint16', readOnly: true },
  { address: 1, name: '当前温度', dataType: 'int16', decimalPoints: 1, unit: '℃', readOnly: true },
  { address: 2, name: '烟雾报警阈值', dataType: 'uint16', readOnly: false },
  { address: 3, name: '烟雾报警标志', dataType: 'bool', readOnly: true },
  {
    address: 4,
    name: '温度报警阈值',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '℃',
    readOnly: false
  },
  { address: 5, name: '温度报警标志', dataType: 'bool', readOnly: true },
  { address: 6, name: '语音音量大小', dataType: 'uint16', readOnly: false, min: 0, max: 30 },
  {
    address: 7,
    name: '循环报警时间间隔',
    dataType: 'uint16',
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  { address: 8, name: '满仓报警是否亮灯', dataType: 'bool', readOnly: false },
  { address: 9, name: '烟雾报警是否亮灯', dataType: 'bool', readOnly: false },
  { address: 10, name: '温度报警是否亮灯', dataType: 'bool', readOnly: false },
  { address: 11, name: '满仓是否语音播报', dataType: 'bool', readOnly: false },
  // 时间参数组1-4
  {
    address: 12,
    name: '伸出时间1',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 13,
    name: '开门保持时间1',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 14,
    name: '关门停顿时间1',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 15,
    name: '伸出时间2',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 16,
    name: '开门保持时间2',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 17,
    name: '关门停顿时间2',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 18,
    name: '伸出时间3',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 19,
    name: '开门保持时间3',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 20,
    name: '关门停顿时间3',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 21,
    name: '伸出时间4',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 22,
    name: '开门保持时间4',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  {
    address: 23,
    name: '关门停顿时间4',
    dataType: 'uint16',
    decimalPoints: 1,
    unit: '秒',
    readOnly: false,
    min: 1,
    max: 60
  },
  // 系统时间
  { address: 24, name: '当前时间小时', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 25, name: '当前时间分钟', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 26, name: '当前时间秒', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  // 门控模块1（地址30-51）
  { address: 30, name: '门1开门指令', dataType: 'bool', readOnly: false },
  { address: 31, name: '门1满仓报警', dataType: 'bool', readOnly: true },
  { address: 32, name: '门1定时使能1', dataType: 'bool', readOnly: false },
  { address: 33, name: '门1定时使能2', dataType: 'bool', readOnly: false },
  { address: 34, name: '门1定时使能3', dataType: 'bool', readOnly: false },
  { address: 35, name: '门1定时使能4', dataType: 'bool', readOnly: false },
  { address: 36, name: '门1开始小时1', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 37, name: '门1开始小时2', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 38, name: '门1开始小时3', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 39, name: '门1开始小时4', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 40, name: '门1开始分钟1', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 41, name: '门1开始分钟2', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 42, name: '门1开始分钟3', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 43, name: '门1开始分钟4', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 44, name: '门1关闭小时1', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 45, name: '门1关闭小时2', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 46, name: '门1关闭小时3', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 47, name: '门1关闭小时4', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 48, name: '门1关闭分钟1', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 49, name: '门1关闭分钟2', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 50, name: '门1关闭分钟3', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 51, name: '门1关闭分钟4', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  // 门控模块2（地址52-73）
  { address: 52, name: '门2开门指令', dataType: 'bool', readOnly: false },
  { address: 53, name: '门2满仓报警', dataType: 'bool', readOnly: true },
  { address: 54, name: '门2定时使能1', dataType: 'bool', readOnly: false },
  { address: 55, name: '门2定时使能2', dataType: 'bool', readOnly: false },
  { address: 56, name: '门2定时使能3', dataType: 'bool', readOnly: false },
  { address: 57, name: '门2定时使能4', dataType: 'bool', readOnly: false },
  { address: 58, name: '门2开始小时1', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 59, name: '门2开始小时2', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 60, name: '门2开始小时3', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 61, name: '门2开始小时4', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 62, name: '门2开始分钟1', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 63, name: '门2开始分钟2', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 64, name: '门2开始分钟3', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 65, name: '门2开始分钟4', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 66, name: '门2关闭小时1', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 67, name: '门2关闭小时2', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 68, name: '门2关闭小时3', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 69, name: '门2关闭小时4', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 70, name: '门2关闭分钟1', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 71, name: '门2关闭分钟2', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 72, name: '门2关闭分钟3', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 73, name: '门2关闭分钟4', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  // 门控模块3（地址74-95）
  { address: 74, name: '门3开门指令', dataType: 'bool', readOnly: false },
  { address: 75, name: '门3满仓报警', dataType: 'bool', readOnly: true },
  { address: 76, name: '门3定时使能1', dataType: 'bool', readOnly: false },
  { address: 77, name: '门3定时使能2', dataType: 'bool', readOnly: false },
  { address: 78, name: '门3定时使能3', dataType: 'bool', readOnly: false },
  { address: 79, name: '门3定时使能4', dataType: 'bool', readOnly: false },
  { address: 80, name: '门3开始小时1', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 81, name: '门3开始小时2', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 82, name: '门3开始小时3', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 83, name: '门3开始小时4', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 84, name: '门3开始分钟1', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 85, name: '门3开始分钟2', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 86, name: '门3开始分钟3', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 87, name: '门3开始分钟4', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 88, name: '门3关闭小时1', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 89, name: '门3关闭小时2', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 90, name: '门3关闭小时3', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 91, name: '门3关闭小时4', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 92, name: '门3关闭分钟1', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 93, name: '门3关闭分钟2', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 94, name: '门3关闭分钟3', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 95, name: '门3关闭分钟4', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  // 门控模块4（地址96-117） // 注释修正为 门控模块4
  { address: 96, name: '门4开门指令', dataType: 'bool', readOnly: false },
  { address: 97, name: '门4满仓报警', dataType: 'bool', readOnly: true },
  { address: 98, name: '门4定时使能1', dataType: 'bool', readOnly: false },
  { address: 99, name: '门4定时使能2', dataType: 'bool', readOnly: false },
  { address: 100, name: '门4定时使能3', dataType: 'bool', readOnly: false },
  { address: 101, name: '门4定时使能4', dataType: 'bool', readOnly: false },
  { address: 102, name: '门4开始小时1', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 103, name: '门4开始小时2', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 104, name: '门4开始小时3', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 105, name: '门4开始小时4', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 106, name: '门4开始分钟1', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 107, name: '门4开始分钟2', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 108, name: '门4开始分钟3', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 109, name: '门4开始分钟4', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 110, name: '门4关闭小时1', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 111, name: '门4关闭小时2', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 112, name: '门4关闭小时3', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 113, name: '门4关闭小时4', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 114, name: '门4关闭分钟1', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 115, name: '门4关闭分钟2', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 116, name: '门4关闭分钟3', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 117, name: '门4关闭分钟4', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  // 照明定时控制 (地址 118, 119 在表格中为 "无", 已跳过)
  { address: 120, name: '定时照明使能', dataType: 'bool', readOnly: false },
  { address: 121, name: '开启小时', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 122, name: '开启分钟', dataType: 'uint16', readOnly: false, min: 0, max: 59 },
  { address: 123, name: '关闭小时', dataType: 'uint16', readOnly: false, min: 0, max: 23 },
  { address: 124, name: '关闭分钟', dataType: 'uint16', readOnly: false, min: 0, max: 59 }
] as const

export type TRegisterConfigNames = (typeof registerConfigs)[number]['name']

export enum MEDIA_TYPE {
  // 全屏广告
  app_ads_slider = 'app_ads_slider',
  // 首页广告
  app_home_slider = 'app_home_slider'
}
